# ค่าตั้งต้น สามารถถูก override ด้วยพารามิเตอร์ CLI
device: auto        # auto | cpu | cuda:0
model: yolov8n.pt   # หรือ path โมเดลของคุณ
conf: 0.5
imgsz: 640
source: webcam      # webcam | realsense | path ไฟล์
webcam_index: 0
show: true
save: false

# ส่งข้อมูลไป KUKA ผ่าน UDP/TCP (ปิดเป็นค่าเริ่มต้น)
send_to_kuka: false
kuka:
  host: 127.0.0.1
  port: 30010
  protocol: udp      # udp | tcp
